-- Omok database (Postgres / Supabase). Applied by tools/db_setup.py; safe to re-run.
-- Row level security is on with no policies: only the server (DATABASE_URL, a
-- privileged role) reads and writes; Supabase's public REST API sees nothing.

CREATE TABLE IF NOT EXISTS leaderboard (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    score INTEGER NOT NULL,
    level INTEGER NOT NULL,
    stones INTEGER NOT NULL,
    date TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS game_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moves TEXT NOT NULL,
    winner INTEGER NOT NULL,
    game_mode TEXT,
    level INTEGER,
    stone_count INTEGER,
    date TEXT,
    time TEXT
);

ALTER TABLE leaderboard ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_records ENABLE ROW LEVEL SECURITY;

-- Pattern learning was removed (v3.3.0): drop its tables and column
DROP TABLE IF EXISTS pattern_stats, weight_history, composite_pattern_stats,
    cluster_pattern_stats, cluster_connection_stats;
ALTER TABLE game_records DROP COLUMN IF EXISTS analyzed;
