-- Omok database (Postgres / Supabase). Applied by tools/db_setup.py; safe to re-run.
-- Row level security is on with no policies: only the server (DATABASE_URL, a
-- privileged role) reads and writes; Supabase's public REST API sees nothing.

CREATE TABLE IF NOT EXISTS leaderboard (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    score INTEGER NOT NULL,
    level INTEGER NOT NULL,
    stones INTEGER NOT NULL,
    date TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS game_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moves TEXT NOT NULL,
    winner INTEGER NOT NULL,
    game_mode TEXT,
    level INTEGER,
    stone_count INTEGER,
    date TEXT,
    time TEXT,
    analyzed INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS pattern_stats (
    pattern TEXT PRIMARY KEY,
    win_count INTEGER DEFAULT 0,
    total_count INTEGER DEFAULT 0,
    current_weight DOUBLE PRECISION,
    attack_weight DOUBLE PRECISION,
    defense_weight DOUBLE PRECISION,
    attack_win_count INTEGER DEFAULT 0,
    attack_total_count INTEGER DEFAULT 0,
    defense_win_count INTEGER DEFAULT 0,
    defense_total_count INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS weight_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern TEXT NOT NULL,
    attack_weight DOUBLE PRECISION,
    defense_weight DOUBLE PRECISION,
    game_count INTEGER,
    recorded_at TEXT
);

CREATE TABLE IF NOT EXISTS composite_pattern_stats (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern_type TEXT NOT NULL,
    game_id INTEGER,
    move_number INTEGER,
    player INTEGER,
    resulted_in_win INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS cluster_pattern_stats (
    pattern_id TEXT PRIMARY KEY,
    win_count INTEGER DEFAULT 0,
    total_count INTEGER DEFAULT 0,
    attack_weight DOUBLE PRECISION,
    defense_weight DOUBLE PRECISION,
    attack_win_count INTEGER DEFAULT 0,
    attack_total_count INTEGER DEFAULT 0,
    defense_win_count INTEGER DEFAULT 0,
    defense_total_count INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS cluster_connection_stats (
    connection_type TEXT PRIMARY KEY,
    win_count INTEGER DEFAULT 0,
    total_count INTEGER DEFAULT 0,
    attack_weight DOUBLE PRECISION,
    defense_weight DOUBLE PRECISION,
    attack_win_count INTEGER DEFAULT 0,
    attack_total_count INTEGER DEFAULT 0,
    defense_win_count INTEGER DEFAULT 0,
    defense_total_count INTEGER DEFAULT 0
);

ALTER TABLE leaderboard ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE pattern_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE weight_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE composite_pattern_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE cluster_pattern_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE cluster_connection_stats ENABLE ROW LEVEL SECURITY;
